### PR TITLE
Added URL Shortener Script in Python

### PR DESCRIPTION
**Pull request by prathimacode-hub**
It's a python script of URL Shortener, a task which most people use it in day to day lives.

### CODE REVIEW

**Comment by subhayu99** [comment]
Thank You for your help @prathimacode-hub

**Comment by subhayu99** [comment]
Ohh! Btw, add yourself to the contributor's list by editing the [README](https://github.com/subhayu99/PyScripts/blob/master/README.md) file.

**Comment by prathimacode-hub** [comment]
Ok. Thank you for providing this opportunity. Yes, I will add it. @subhayu99

**Comment by prathimacode-hub** [comment]
Can I know how to get the img src link in avatar? @subhayu99

**Comment by subhayu99** [comment]
> Can I know how to get the img src link in avatar? @subhayu99

https://avatars.githubusercontent.com/u/74645302?v=4 this is the link to your avatar. Anyways, you can find it by pressing your profile picture on your GitHub Profile.

**Comment by prathimacode-hub** [comment]
> > Can I know how to get the img src link in avatar? @subhayu99
> 
> https://avatars.githubusercontent.com/u/74645302?v=4 this is the link to your avatar. Anyways, you can find it by pressing your profile picture on your GitHub Profile.

Thank you for letting me know. I have added up. @subhayu99

**Pull request merged**
